// Common departments in colleges/universities
export const DEPARTMENTS = [
  "Computer Science & Engineering",
  "Information Technology",
  "Electronics & Communication Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Biotechnology",
  "Business Administration",
  "Commerce",
  "Economics",
  "Mathematics",
  "Physics",
  "Chemistry",
  "English Literature",
  "Psychology",
  "Sociology",
  "Political Science",
  "History",
  "Fine Arts",
  "Design",
  "Architecture",
  "Medicine",
  "Pharmacy",
  "Nursing",
  "Law",
  "Other",
];

// Common batch years (current and past few years)
export const BATCHES = [
  "2028",
  "2027",
  "2026",
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
];

// Common skills and expertise areas
export const SKILLS = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Rust",
  "TypeScript",
  "Swift",
  "Kotlin",
  "Dart",

  // Web Development
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Next.js",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Bootstrap",
  "jQuery",

  // Mobile Development
  "React Native",
  "Flutter",
  "Android Development",
  "iOS Development",
  "Xamarin",

  // Databases
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "SQLite",
  "Oracle",
  "Firebase",

  // Cloud & DevOps
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "GitHub Actions",

  // Data Science & AI
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "Artificial Intelligence",
  "Natural Language Processing",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "Scikit-learn",

  // Design & Creative
  "UI/UX Design",
  "Graphic Design",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Canva",
  "Sketch",

  // Other Technical Skills
  "Git",
  "Linux",
  "Cybersecurity",
  "Blockchain",
  "IoT",
  "Game Development",
  "DevOps",
  "System Design",
  "API Development",
  "Microservices",

  // Business & Management
  "Project Management",
  "Digital Marketing",
  "Content Writing",
  "SEO",
  "Social Media Marketing",
  "Business Analysis",
  "Leadership",
  "Communication",
  "Public Speaking",
  "Team Management",

  // Academic Subjects
  "Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Economics",
  "Finance",
  "Accounting",
  "Research",
  "Academic Writing",
];
