// Common predefined options for semesters and subjects
export const SEMESTERS = [
  "1st Semester",
  "2nd Semester",
  "3rd Semester",
  "4th Semester",
  "5th Semester",
  "6th Semester",
  "7th Semester",
  "8th Semester",
];

export const SUBJECTS = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Programming Fundamentals",
  "Data Structures",
  "Algorithms",
  "Database Management Systems",
  "Operating Systems",
  "Computer Networks",
  "Software Engineering",
  "Object Oriented Programming",
  "Web Development",
  "Machine Learning",
  "Artificial Intelligence",
  "Computer Graphics",
  "System Design",
  "Digital Logic",
  "Microprocessors",
  "Theory of Computation",
  "Compiler Design",
  "Mobile Application Development",
  "Cybersecurity",
  "Cloud Computing",
  "Big Data Analytics",
  "Internet of Things",
  "Embedded Systems",
];
